//======================================================================================================================
/*
 POLYFLOAT - Extended precision floating points
 Copyright : POLYFLOAT Contributors & Maintainers
 SPDX-License-Identifier: BSL-1.0
*/
//======================================================================================================================
#pragma once

#include <polyfloat/core_constants.hpp>
#include <polyfloat/module/core/abs.hpp>
#include <polyfloat/module/core/absmax.hpp>
#include <polyfloat/module/core/absmin.hpp>
#include <polyfloat/module/core/add.hpp>
#include <polyfloat/module/core/average.hpp>
#include <polyfloat/module/core/ceil.hpp>
#include <polyfloat/module/core/chi.hpp>
#include <polyfloat/module/core/clamp.hpp>
#include <polyfloat/module/core/convert.hpp>
#include <polyfloat/module/core/copysign.hpp>
#include <polyfloat/module/core/dec.hpp>
#include <polyfloat/module/core/dist.hpp>
#include <polyfloat/module/core/div.hpp>
#include <polyfloat/module/core/epsilon.hpp>
#include <polyfloat/module/core/exponent.hpp>
#include <polyfloat/module/core/floor.hpp>
#include <polyfloat/module/core/fma.hpp>
#include <polyfloat/module/core/fnma.hpp>
#include <polyfloat/module/core/fmod.hpp>
#include <polyfloat/module/core/frac.hpp>
#include <polyfloat/module/core/frexp.hpp>
#include <polyfloat/module/core/heaviside.hpp>
#include <polyfloat/module/core/horner.hpp>
#include <polyfloat/module/core/if_else.hpp>
#include <polyfloat/module/core/inc.hpp>
#include <polyfloat/module/core/is_denormal.hpp>
#include <polyfloat/module/core/is_equal.hpp>
#include <polyfloat/module/core/is_eqz.hpp>
#include <polyfloat/module/core/is_eqmz.hpp>
#include <polyfloat/module/core/is_eqpz.hpp>
#include <polyfloat/module/core/is_even.hpp>
#include <polyfloat/module/core/is_finite.hpp>
#include <polyfloat/module/core/is_flint.hpp>
#include <polyfloat/module/core/is_greater.hpp>
#include <polyfloat/module/core/is_greater_equal.hpp>
#include <polyfloat/module/core/is_gtz.hpp>
#include <polyfloat/module/core/is_infinite.hpp>
#include <polyfloat/module/core/is_less.hpp>
#include <polyfloat/module/core/is_less_equal.hpp>
#include <polyfloat/module/core/is_lessgreater.hpp>
#include <polyfloat/module/core/is_ltz.hpp>
#include <polyfloat/module/core/is_minf.hpp>
#include <polyfloat/module/core/is_nan.hpp>
#include <polyfloat/module/core/is_negative.hpp>
#include <polyfloat/module/core/is_nemz.hpp>
#include <polyfloat/module/core/is_nepz.hpp>
#include <polyfloat/module/core/is_nez.hpp>
#include <polyfloat/module/core/is_ngez.hpp>
#include <polyfloat/module/core/is_ngtz.hpp>
#include <polyfloat/module/core/is_nlez.hpp>
#include <polyfloat/module/core/is_nltz.hpp>
#include <polyfloat/module/core/is_not_denormal.hpp>
#include <polyfloat/module/core/is_not_equal.hpp>
#include <polyfloat/module/core/is_not_finite.hpp>
#include <polyfloat/module/core/is_not_flint.hpp>
#include <polyfloat/module/core/is_not_greater.hpp>
#include <polyfloat/module/core/is_not_greater_equal.hpp>
#include <polyfloat/module/core/is_not_infinite.hpp>
#include <polyfloat/module/core/is_not_less.hpp>
#include <polyfloat/module/core/is_not_less_equal.hpp>
#include <polyfloat/module/core/is_not_nan.hpp>
#include <polyfloat/module/core/is_odd.hpp>
#include <polyfloat/module/core/is_ordered.hpp>
#include <polyfloat/module/core/is_pinf.hpp>
#include <polyfloat/module/core/is_positive.hpp>
#include <polyfloat/module/core/is_pow2.hpp>
#include <polyfloat/module/core/is_unit.hpp>
#include <polyfloat/module/core/is_unordered.hpp>
#include <polyfloat/module/core/ldexp.hpp>
#include <polyfloat/module/core/lerp.hpp>
#include <polyfloat/module/core/mantissa.hpp>
#include <polyfloat/module/core/max.hpp>
#include <polyfloat/module/core/min.hpp>
#include <polyfloat/module/core/minus.hpp>
#include <polyfloat/module/core/modf.hpp>
#include <polyfloat/module/core/mul.hpp>
#include <polyfloat/module/core/nearest.hpp>
#include <polyfloat/module/core/negate.hpp>
#include <polyfloat/module/core/negatenz.hpp>
#include <polyfloat/module/core/next.hpp>
#include <polyfloat/module/core/parts.hpp>
#include <polyfloat/module/core/prev.hpp>
#include <polyfloat/module/core/rec.hpp>
#include <polyfloat/module/core/reldist.hpp>
#include <polyfloat/module/core/rsqrt.hpp>
#include <polyfloat/module/core/sign.hpp>
#include <polyfloat/module/core/signnz.hpp>
#include <polyfloat/module/core/sqr.hpp>
#include <polyfloat/module/core/sqrt.hpp>
#include <polyfloat/module/core/sub.hpp>
#include <polyfloat/module/core/trunc.hpp>
#include <polyfloat/module/core/two_add.hpp>
