var NAVTREEINDEX0 =
{
"conceptplf_1_1concepts_1_1polyfloat.html":[4,4,0,0,0],
"conceptplf_1_1concepts_1_1real.html":[4,4,0,0,1],
"concepts.html":[4,4],
"group__constants.html":[4,1],
"group__functions.html":[4,2],
"group__traits.html":[4,3],
"group__types.html":[4,0],
"index.html":[],
"index.html#autotoc_md0":[0],
"index.html#autotoc_md1":[1],
"index.html#autotoc_md2":[2],
"index.html#autotoc_md3":[2,0],
"index.html#autotoc_md4":[2,1],
"index.html#autotoc_md5":[2,2],
"index.html#autotoc_md6":[2,3],
"index.html#autotoc_md7":[2,4],
"licence.html":[5,0],
"pages.html":[],
"usergroup0.html":[3],
"usergroup1.html":[4],
"usergroup2.html":[5]
};
