##======================================================================================================================
##  Polyfloat - Extended precision floating points
##  Copyright : POLYFLOAT Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: Unit Tests
on:
  pull_request:
    branches:
      - main

concurrency:
  group: polyfloat-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanitizer-tests:
    name: Sanitizers
    uses: jfalcou/copacabana/.github/workflows/sanitizers.yml@3337f916bb581d0829909976773f7a2ee827a25c # v4
    with:
      build-targets: doc.exe unit.exe
      test-targets: doc|unit

  coverage-report:
    name: Coverage
    uses: jfalcou/copacabana/.github/workflows/coverage.yml@3337f916bb581d0829909976773f7a2ee827a25c # v4
    with:
      project: polyfloat
      build-targets: polyfloat-test

  linux-tests:
    name: Linux
    needs: sanitizer-tests
    uses: ./.github/workflows/linux.yml

  macos-tests:
    name: MacOS
    needs: sanitizer-tests
    uses: ./.github/workflows/macos.yml
