##======================================================================================================================
##  Polyfloat - Extended precision floating points
##  Copyright : POLYFLOAT Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: Unit Tests
on:
  pull_request:
    branches:
      - main

concurrency:
  group: polyfloat-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanitizer-tests:
    name: Sanitizers
    uses: ./.github/workflows/sanitizers.yml

  coverage-report:
    name: Coverage
    uses: ./.github/workflows/coverage.yml

  linux-tests:
    name: Linux
    needs: sanitizer-tests
    uses: ./.github/workflows/linux.yml

  macos-tests:
    name: MacOS
    needs: sanitizer-tests
    uses: ./.github/workflows/macos.yml
