##======================================================================================================================
##  Polyfloat - Extended precision floating points
##  Copyright : POLYFLOAT Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: POLYFLOAT Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    permissions:
      contents: write
    uses: jfalcou/copacabana/.github/workflows/documentation.yml@47475b1b93abdab72025105c3c0a683adfd6b866 # v3
    with:
      project: polyfloat
      coverage: true
