##======================================================================================================================
##  Polyfloat - Extended precision floating points
##  Copyright : POLYFLOAT Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: POLYFLOAT Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    permissions:
      contents: write
    uses: jfalcou/copacabana/.github/workflows/documentation.yml@bdd4698a6b7653510904e7e408298c574591af69 # v5
    with:
      project: polyfloat
      coverage: true
