##======================================================================================================================
##  Polyfloat - Extended precision floating points
##  Copyright : POLYFLOAT Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: POLYFLOAT Linux Tests
on:
  workflow_call:

jobs:
  linux:
    name: ${{ matrix.compiler.name }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v10
      options: -u root
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "gcc"        , preset: "gcc"        }
          - { name: "clang"      , preset: "clang"      }
          - { name: "gcc avx2"   , preset: "gcc-avx2"   }
          - { name: "clang avx2" , preset: "clang-avx2" }

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: jfalcou/copacabana/.github/actions/config@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: Debug
          preset: ${{ matrix.compiler.preset }}
          targets: doc.exe unit.exe

      - name: Run Doc Tests
        uses: jfalcou/copacabana/.github/actions/test@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: Debug
          preset: ${{ matrix.compiler.preset }}
          targets: ^doc.*

      - name: Run Unit Tests
        uses: jfalcou/copacabana/.github/actions/test@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: Debug
          preset: ${{ matrix.compiler.preset }}
          targets: ^unit.*
